// English translations
const en = {
    // ---- NAV ----
    nav_logo: '<span class="text-primary">COACH</span> MAHMOUD',
    nav_home: "Home",
    nav_about: "About",
    nav_transformations: "Transformations",
    nav_services: "Services",
    nav_pricing: "Pricing",
    nav_faq: "FAQ",
    nav_cta: "Start Now",

    // ---- HERO ----
    badge_premium: "PREMIUM PERSONAL COACHING",
    hero_title_top: "SHAPE YOUR",
    hero_title_main: "ULTIMATE",
    hero_title_highlight: "PHYSIQUE",
    hero_subtitle: "Achieve sustainable, life-changing results with science-backed customized training programs, tailored nutrition plans, and 1-on-1 daily accountability.",
    hero_benefit_1: "Science-Backed Workout Protocols",
    hero_benefit_2: "100% Tailored Meals & Custom Dieting",
    hero_benefit_3: "Daily 1-on-1 WhatsApp Coaching",
    hero_cta_start: "Start Your Transformation",
    hero_cta_packages: "View Packages",
    hero_scroll: "Scroll",
    hero_float_cert: "ISSA Certified",
    hero_float_cert_sub: "Elite Personal Trainer",
    hero_float_clients: "500+ Clients",
    hero_float_clients_sub: "Real Transformations",

    // ---- STATS ----
    stat_years: "Years Experience",
    stat_clients: "Clients Trained",
    stat_success: "Success Rate (%)",
    stat_certs: "Certifications",

    // ---- ABOUT ----
    about_tagline: "Meet Your Coach",
    about_title: "About Coach Mahmoud Hamada",
    about_subtitle: "Empowering You To Achieve Peak Performance",
    about_p1: "I am Coach Mahmoud Hamada, a certified fitness specialist, bodybuilding professional, and sports nutrition expert with over 8 years of active industry experience. My coaching philosophy revolves around a simple yet powerful fact: <strong>there is no one-size-fits-all training protocol.</strong>",
    about_p2: "Every individual holds unique biometrics, work schedules, metabolic rates, and personal limits. I combine modern sports science with strict accountability to build a lifestyle that yields lasting physical change—without leaving you starving or chronically fatigued.",
    spec_1_title: "Tailored Workout Architecture",
    spec_1_desc: "Custom programs modeled around your posture, strengths, and goals.",
    spec_2_title: "Advanced Nutrition & Macro Planning",
    spec_2_desc: "Flexible dieting plans tailored to your food preferences and metabolism.",
    specialty_1_title: "Fat Loss & Shredding",
    specialty_1_desc: "Burn fat efficiently while fully maintaining lean muscle mass.",
    specialty_2_title: "Hypertrophy & Muscle Gain",
    specialty_2_desc: "Targeted hyper-trophy cycles for maximum density and muscular growth.",
    specialty_3_title: "Body Recomposition",
    specialty_3_desc: "Build muscle and burn fat simultaneously through precise caloric matching.",
    specialty_4_title: "Lifestyle & Longevity",
    specialty_4_desc: "Enhance cardiovascular metrics, flexibility, and sleep quality.",

    // ---- PROCESS / HOW IT WORKS ----
    process_tagline: "The Process",
    process_title: "How We Get You There",
    step_1_title: "Reach Out",
    step_1_desc: "Message Coach Mahmoud on WhatsApp and tell him your goal, your struggles, and where you're starting from.",
    step_2_title: "Free Assessment",
    step_2_desc: "A real conversation about your body, your schedule, and your history — no templates, no guesswork.",
    step_3_title: "Custom Plan",
    step_3_desc: "A training and nutrition plan built for your body, your equipment, and your life — not a copy-paste PDF.",
    step_4_title: "Weekly Check-Ins",
    step_4_desc: "Direct check-ins, form reviews, and plan adjustments every week until you hit the number you came for.",

    // ---- ID CARDS ----
    idcards_tagline: "Official Membership Cards",
    idcards_title: "Trainer ID Cards",
    alt_idcard: "Coach Mahmoud Hamada official trainer ID card",
    idcard_1_title: "Nutrition for Sports – ID Card",
    idcard_1_issuer: "Olympic Academy for Sports Leaders",
    idcard_2_title: "Certified Fitness Trainer (CFT) – ID Card",
    idcard_2_issuer: "Olympic Academy for Sports Leaders",
    idcard_3_title: "Certified Fitness Trainer – Membership Card",
    idcard_3_issuer: "PRO FTT Academy for Sports Facilities & Rehabilitation",

    // ---- CERTIFICATES ----
    cert_tagline: "Academic & Professional Background",
    cert_title: "Credentials & Certifications",
    cert_azhar_title: "Bachelor's Degree in Physical Education",
    cert_azhar_issuer: "Al-Azhar University",
    cert_expand: "Click to Expand",
    cert_2_title: "Nutrition for Athletes",
    cert_2_issuer: "Olympic Academy for Sports Leaders",
    cert_3_title: "1st Place - Under 23 Championship",
    cert_3_issuer: "Egyptian Bodybuilding Federation",
    cert_4_title: "Certified Fitness Trainer (CFT)",
    cert_4_issuer: "Olympic Academy for Sports Leaders",
    cert_5_title: "Certified Fitness Trainer (CFT)",
    cert_5_issuer: "Egyptian Sports Culture Association",
    cert_6_title: "1st Place - Second Division Championship",
    cert_6_issuer: "Egyptian Bodybuilding Federation",
    cert_7_title: "Nutrition for Athletes",
    cert_7_issuer: "Olympic Academy for Sports Leaders",
    cert_8_title: "Certified Fitness Trainer (CFT)",
    cert_8_issuer: "Olympic Academy for Sports Leaders",

    // ---- TRANSFORMATIONS ----
    trans_tagline: "Real Clients. Real Proof.",
    trans_title: "Client Transformations",
    trans_start_story: "Start Your Story",
    trans_1_tag: "Fat Loss & Muscle Gain",
    trans_1_duration: "12 Weeks",
    trans_1_name: "Ahmed's Transformation",
    trans_1_desc: "Ahmed reduced body fat from 24% to 11% while gaining solid lean mass, fully rebuilding strength in compound lifts.",
    trans_1_m1_label: "Weight Change:",
    trans_1_m1_val: "-14kg",
    trans_1_m2_label: "Muscle Gained:",
    trans_1_m2_val: "+3.2kg",
    trans_2_tag: "Body Recomposition",
    trans_2_duration: "16 Weeks",
    trans_2_name: "Sarah's Transformation",
    trans_2_desc: "Sarah completely reshaped her posture, sculpted core definition, and improved functional endurance and metabolic rate.",
    trans_2_m1_label: "Weight Change:",
    trans_2_m1_val: "-8.5kg",
    trans_2_m2_label: "Body Fat Change:",
    trans_2_m2_val: "-12.5%",

    // ---- TRANSFORMATIONS (SECTION HEADER) ----
    transformations_tagline: "Real Proof",
    transformations_title: "Success Stories",

    // ---- SERVICES ----
    services_tagline: "How We Work Together",
    services_title: "Coaching Architecture",
    svc_1_title: "Bespoke Workout Design",
    svc_1_desc: "No generic PDF files. Every routine is mapped dynamically based on your available equipment, structural biomechanics, joints mobility, and physical targets.",
    svc_2_title: "Custom Diet Program For Your Goal",
    svc_2_desc: "A comprehensive diet plan specially designed to suit your body's needs and goals, with flexible food choices to ensure consistency and achieve the best results.",
    svc_3_title: "Daily Follow-Up & Accountability",
    svc_3_desc: "Direct communication to update weight charts, track training progression logs, evaluate form via videos, and handle dynamic weekly nutrition modifications.",

    // ---- PRICING ----
    pricing_tagline: "Choose Your Pathway",
    pricing_title: "Coaching Programs",
    price_ribbon: "RECOMMENDED",
    pkg_1_name: "Basic Coaching",
    pkg_1_period: "/ Month",
    pkg_1_price: "600 EGP",
    pkg_1_desc: "An organized and effective start for anyone looking to transform their body the right way, without a high cost.",
    pkg_1_f1: "Custom training program tailored to your level and goal",
    pkg_1_f2: "Diet plan suited to your needs and budget",
    pkg_1_f3: "Program adjustments based on your progress",
    pkg_1_f4: "Weekly follow-up",
    pkg_1_f5: "WhatsApp support",
    pkg_1_f6: "Query responses and commitment tracking",
    pkg_1_f7: "Continuous guidance to correct mistakes",
    pkg_1_f8: "Initial assessment to determine your starting point",
    pkg_1_f9: "Clear and easy-to-apply plan",

    pkg_2_name: "Premium Coaching",
    pkg_2_period: "/ Month",
    pkg_2_price: "1200 EGP",
    pkg_2_desc: "The ideal choice for those who want real commitment, continuous follow-up, and a clear transformation in their body and performance.",
    pkg_2_f1: "Fully customized training program based on your goal",
    pkg_2_f2: "Precise diet plan with ingredients and macros",
    pkg_2_f3: "Daily follow-up",
    pkg_2_f4: "Daily WhatsApp support",
    pkg_2_f5: "Fast response to inquiries",
    pkg_2_f6: "Video form review and technique correction",
    pkg_2_f7: "Program adjustment based on your response",
    pkg_2_f8: "Two calls per month",
    pkg_2_f9: "Weight and measurements tracking",
    pkg_2_f10: "Continuous progress evaluation",
    pkg_2_f11: "Ongoing plan modifications based on results",

    pkg_3_name: "3-Month Transformation",
    pkg_3_period: "/ 3 Months",
    pkg_3_price: "1800 EGP",
    pkg_3_desc: "3 months of real commitment with a clear plan and continuous follow-up to build a lasting change.",
    pkg_3_f1: "Training program renewed monthly",
    pkg_3_f2: "Precise diet plan with ingredients and macros",
    pkg_3_f3: "Weekly follow-up",
    pkg_3_f4: "Plan adjustment based on your needs and progress",
    pkg_3_f5: "Weight and measurements tracking",
    pkg_3_f6: "Before / After photos",
    pkg_3_f7: "WhatsApp support",
    pkg_3_f8: "Custom diet and training program design",
    pkg_3_f9: "Continuous progress evaluation",
    pkg_3_f10: "Commitment and habits review",
    pkg_3_f11: "Continuous guidance throughout the subscription",

    pkg_4_name: "VIP Coaching",
    pkg_4_period: "/ Month",
    pkg_4_price: "1000 EGP",
    pkg_4_desc: "If you want a coach who tracks your journey day by day and intervenes quickly with every change in your response, this is your package.",
    pkg_4_f1: "Daily follow-up",
    pkg_4_f2: "Fast response via WhatsApp",
    pkg_4_f3: "Fully customized training and diet program",
    pkg_4_f4: "Precise diet plan with ingredients and macros",
    pkg_4_f5: "Immediate program adjustments based on response",
    pkg_4_f6: "Video form review",
    pkg_4_f7: "Weight and measurements tracking",
    pkg_4_f8: "3 personal calls per month",
    pkg_4_f9: "Daily commitment tracking",
    pkg_4_f10: "Continuous results analysis",
    pkg_4_f11: "Real-time problem and obstacle solving",
    pkg_4_f12: "Continuous plan modifications",

    pkg_5_name: "VIP 3-Month Transformation",
    pkg_5_period: "/ 3 Months",
    pkg_5_price: "2500 EGP",
    pkg_5_desc: "The highest level of personal follow-up — 3 months of intensive work on training, nutrition, performance, and results.",
    pkg_5_f1: "Intensive daily follow-up",
    pkg_5_f2: "Fast response via WhatsApp",
    pkg_5_f3: "Fully customized training and diet system for your goal",
    pkg_5_f4: "Precise diet plan with ingredients and macros",
    pkg_5_f5: "Immediate program adjustments based on body response",
    pkg_5_f6: "Video form review",
    pkg_5_f7: "Weight and measurements tracking",
    pkg_5_f8: "4 calls per month",
    pkg_5_f9: "Continuous progress evaluation",
    pkg_5_f10: "Commitment and habits tracking",
    pkg_5_f11: "Continuous plan review and development",
    pkg_5_f12: "Modifications based on results and circumstances",
    pkg_5_f13: "Full follow-up throughout the 3 months",

    pkg_6_name: "Military Preparation",
    pkg_6_period: "/ Month",
    pkg_6_price: "1200 EGP",
    pkg_6_desc: "A specialized program for those preparing for fitness and military qualification tests, aiming to enter the test in the best physical condition possible.",
    pkg_6_f1: "Current fitness level assessment",
    pkg_6_f2: "Custom training program for military preparation",
    pkg_6_f3: "Running and endurance training",
    pkg_6_f4: "Strength and muscular endurance development",
    pkg_6_f5: "Push-ups, sit-ups, and pull-ups training as required",
    pkg_6_f6: "Progressive program to raise fitness level",
    pkg_6_f7: "Diet plan suitable for the preparation period",
    pkg_6_f8: "Weekly progress follow-up",
    pkg_6_f9: "Performance correction",
    pkg_6_f10: "Program adjustments based on your level",
    pkg_6_f11: "WhatsApp support",
    pkg_6_f12: "Periodic tests to simulate exam levels",
    pkg_6_f13: "Gradual preparation for physical tests",

    btn_select: "Select Plan",
    btn_get_started: "Get Started",
    btn_unlock_vip: "Unlock VIP",

    // ---- WHY ----
    why_tagline: "The Coaching Difference",
    why_title: "Why Coach Mahmoud?",
    why_1_title: "Certified & Scientific",
    why_1_desc: "Fully certified with international qualifications, avoiding standard workout trends in favor of verified biological and hypertrophy science.",
    why_2_title: "100% Tailored Layouts",
    why_2_desc: "I design your charts from zero. Your foods, schedule, and biomechanical parameters form the core structure of your programs.",
    why_3_title: "Fast Accountability Response",
    why_3_desc: "No waiting days for feedback. Updates and corrections are handled with priority so your progress never stalls.",

    // ---- TESTIMONIALS ----
    test_tagline: "Client Success Stories",
    test_title: "What My Clients Say",
    test_1_text: '"Coaching with Mahmoud has been an absolute game changer. I\'ve struggled to lose fat for years while maintaining strength. Within 12 weeks, he completely overhauled my nutrition and custom training program, and the fat literally melted away."',
    test_1_achievement: "Lost 14kg & Gained Muscle",
    test_2_text: '"The level of detail Coach Mahmoud puts into the weekly updates is unmatched. He didn\'t just give me diet rules; he explained the macros, helped me modify choices when traveling, and kept me strictly on track. Recommended for anyone looking for serious results."',
    test_2_achievement: "12.5% Body Fat Reduction",
    test_3_text: '"As a busy professional, finding time to train was impossible. Coach Mahmoud created a highly effective 45-minute home workout program and taught me flexible dieting that fits my schedule. Extremely professional and communicative."',
    test_3_achievement: "Improved Muscle Definition",

    // ---- TESTIMONIALS (SECTION HEADER + CARDS) ----
    testimonials_tagline: "Real Words",
    testimonials_title: "What Clients Say",
        testi_1_text: "I had tried multiple coaches before and couldn't lose weight until I started with Coach Mahmoud Hamada. He really put in the work with me, changed my plan to include foods I love, instead of just a strict diet. Thanks to him, I managed to lose weight and reach my goal.",
    testi_1_name: "Sara",
    testi_2_text: "My goal was to lose weight and change my physique. Thankfully, with Coach Mahmoud, I was able to drop the weight and reach a great level in a short time. The continuous follow-up always kept me motivated to keep going.",
    testi_2_name: "Ahmed",
    testi_3_text: "I thought it was impossible to change my physique after 35. Coach Mahmoud helped me achieve a full body recomposition. I lost fat and built muscle simultaneously without starvation.",
    testi_3_name: "Omar",
    testi_4_text: "I had physical fitness tests for a military academy and was very anxious about running and pull-ups. The program was tailored exactly to the test requirements, and I passed with flying colors.",
    testi_4_name: "Youssef",
    testi_5_text: "After a shoulder injury, I couldn't train for months. Coach Mahmoud started with me from scratch with a rehab program, and now I'm lifting heavier than before with zero pain.",
    testi_5_name: "Khaled",
    testi_6_text: "I have a desk job and my life was completely sedentary. Subscribing with Coach Mahmoud was the best investment in my health. My energy sky-rocketed, my lifestyle changed, and my clothes fit completely differently.",
    testi_6_name: "Mahmoud",
    // ---- FAQ ----
    faq_tagline: "Clear Answers",
    faq_title: "Frequently Asked Questions",
    faq_desc: "Everything you need to know about starting your transformation journey with Coach Mahmoud.",
    faq_1_q: "How fast will I receive my custom workout and meal plans?",
    faq_1_a: "After you submit your initial fitness assessment form and complete your subscription, Coach Mahmoud will conduct a full analysis of your structure, metabolic history, and schedule. Your personalized training and nutrition blueprints will be delivered directly to your WhatsApp dashboard within 48 to 72 hours.",
    faq_2_q: "Can I train if I only have a home setup or minimal weights?",
    faq_2_a: "Yes. Every training plan is built around the equipment you have available. If you only have resistance bands, dumbbells, or just bodyweight, your routine will be optimized for maximum mechanical tension and hypertrophy using home-specific progressions.",
    faq_3_q: "What if I have foods I absolutely dislike or cannot eat?",
    faq_3_a: "I follow a flexible dieting method backed by strict structural macros. In your assessment form, you will outline all food allergies, preferences, and details. Your meal plan is built to only contain foods you enjoy, ensuring the diet is sustainable long-term.",
    faq_4_q: "How do the weekly check-ins and follow-ups work?",
    faq_4_a: "For standard plans, you will submit a weekly check-in sheet detailing weight parameters, measurements, and training performance. Based on this data, Coach Mahmoud adjusts your macros, caloric density, and workout load. For Elite and VIP plans, this tracking and communication is done daily on WhatsApp.",

    // ---- CONTACT ----
    contact_badge: "START TODAY",
    contact_title: "Ready To Transform Your Body & Mind?",
    contact_title_mobile: "Ready To Transform Your Body & Mind?",
    contact_desc: "Fill out the rapid biometric questionnaire below. Once submitted, it will compile your stats and redirect you directly to Coach Mahmoud on WhatsApp to finalize your enrollment.",
    contact_whatsapp_label: "WhatsApp Hotline",
    contact_email_label: "Support Email",
    form_title: "Biometric Assessment",
    form_subtitle: "Enter your metrics below to calculate your tailored coach macros.",
    label_name: "Full Name *",
    label_phone: "Phone Number *",
    label_age: "Age *",
    label_goal: "Goal *",
    label_package: "Suitable Package *",
    label_weight: "Current Weight *",
    label_height: "Height *",
    label_experience: "Training Experience *",
    label_medical: "Do you suffer from injuries or chronic diseases? *",
    label_notes: "Notes",
    placeholder_name: "Enter your full name",
    placeholder_phone: "Enter your phone number",
    placeholder_age: "Enter your age",
    placeholder_goal: "Choose your goal",
    placeholder_package: "Choose a package",
    placeholder_weight: "e.g. 85 kg",
    placeholder_height: "e.g. 180 cm",
    placeholder_experience: "Choose your experience level",
    placeholder_medical: "Choose an answer",
    placeholder_notes: "Any additional details about your goals or condition",
    option_goal_1: "Fat Loss",
    option_goal_2: "Muscle Gain",
    option_goal_3: "Body Recomposition",
    option_goal_4: "General Fitness",
    option_exp_1: "Beginner",
    option_exp_2: "Intermediate",
    option_exp_3: "Advanced",
    option_med_no: "No",
    option_med_yes: "Yes",
    option_pkg_1: "Basic Coaching - 600 EGP/mo",
    option_pkg_2: "Premium Coaching - 1200 EGP/mo",
    option_pkg_3: "3-Month Transformation - 1800 EGP/3mo",
    option_pkg_4: "VIP Coaching - 1000 EGP/mo",
    option_pkg_5: "VIP 3-Month Transformation - 2500 EGP/3mo",
    option_pkg_6: "Military Preparation - 1200 EGP/mo",
    btn_submit: "Send Biometrics on WhatsApp",

    // ---- FOOTER ----
    footer_brand_desc: "Premium 1-on-1 science-backed coaching. Change your physique, build discipline, and unlock your true performance potential.",
    footer_nav_title: "Navigation",
    footer_nav_home: "Home",
    footer_nav_about: "About",
    footer_nav_trans: "Transformations",
    footer_nav_services: "Services",
    footer_nav_pricing: "Pricing Plans",
    footer_nav_contact: "Contact",
    footer_contact_title: "Get In Touch",
    footer_disclaimer_title: "Medical Disclaimer",
    footer_disclaimer_text: "All fitness routines, metabolic suggestions, and nutrition guidelines provided by Coach Mahmoud Hamada are designed strictly for educational and athletic enhancement. Please consult a qualified health provider before commencing any physical transformation protocol.",
    footer_copy: "© 2026 Coach Mahmoud Hamada. All Rights Reserved.",
    footer_tagline: "Designed for elite athletic training.",

    // ---- ALT TEXTS ----
    alt_coach: "Coach Mahmoud Hamada",
    alt_workout: "Coach Mahmoud Hamada Workout",
    alt_cert: "Certified Credential of Coach Mahmoud Hamada",
    alt_trans: "Before and After Client Transformation with Coach Mahmoud",
};