// English translations
const en = {
    // ---- NAV ----
    nav_home: "Home",
    nav_about: "About",
    nav_transformations: "Transformations",
    nav_services: "Services",
    nav_pricing: "Pricing",
    nav_faq: "FAQ",
    nav_cta: "Start Now",

    // ---- HERO ----
    badge_premium: "PREMIUM PERSONAL COACHING",
    hero_title_top: "SHAPE YOUR",
    hero_title_main: "ULTIMATE",
    hero_title_highlight: "PHYSIQUE",
    hero_subtitle: "Achieve sustainable, life-changing results with science-backed customized training programs, tailored nutrition plans, and 1-on-1 daily accountability.",
    hero_benefit_1: "Science-Backed Workout Protocols",
    hero_benefit_2: "100% Tailored Meals & Custom Dieting",
    hero_benefit_3: "Daily 1-on-1 WhatsApp Coaching",
    hero_cta_start: "Start Your Transformation",
    hero_cta_packages: "View Packages",
    hero_scroll: "Scroll",
    hero_float_cert: "ISSA Certified",
    hero_float_cert_sub: "Elite Personal Trainer",
    hero_float_clients: "500+ Clients",
    hero_float_clients_sub: "Real Transformations",

    // ---- STATS ----
    stat_years: "Years Experience",
    stat_clients: "Clients Trained",
    stat_success: "Success Rate (%)",
    stat_certs: "Certifications",

    // ---- ABOUT ----
    about_tagline: "Meet Your Coach",
    about_title: "About Coach Mahmoud Hamada",
    about_subtitle: "Empowering You To Achieve Peak Performance",
    about_p1: "I am Coach Mahmoud Hamada, a certified fitness specialist, bodybuilding professional, and sports nutrition expert with over 8 years of active industry experience. My coaching philosophy revolves around a simple yet powerful fact: <strong>there is no one-size-fits-all training protocol.</strong>",
    about_p2: "Every individual holds unique biometrics, work schedules, metabolic rates, and personal limits. I combine modern sports science with strict accountability to build a lifestyle that yields lasting physical change—without leaving you starving or chronically fatigued.",
    spec_1_title: "Tailored Workout Architecture",
    spec_1_desc: "Custom programs modeled around your posture, strengths, and goals.",
    spec_2_title: "Advanced Nutrition & Macro Planning",
    spec_2_desc: "Flexible dieting plans tailored to your food preferences and metabolism.",
    specialty_1_title: "Fat Loss & Shredding",
    specialty_1_desc: "Burn fat efficiently while fully maintaining lean muscle mass.",
    specialty_2_title: "Hypertrophy & Muscle Gain",
    specialty_2_desc: "Targeted hyper-trophy cycles for maximum density and muscular growth.",
    specialty_3_title: "Body Recomposition",
    specialty_3_desc: "Build muscle and burn fat simultaneously through precise caloric matching.",
    specialty_4_title: "Lifestyle & Longevity",
    specialty_4_desc: "Enhance cardiovascular metrics, flexibility, and sleep quality.",

    // ---- CERTIFICATES ----
    cert_tagline: "Academic & Professional Background",
    cert_title: "Credentials & Certifications",
    cert_expand: "Click to Expand",
    cert_1_title: "Certified Personal Trainer (CPT)",
    cert_1_issuer: "ISSA - International Sports Sciences Association",
    cert_2_title: "Sports Nutritionist Specialist (SNS)",
    cert_2_issuer: "ISSA - International Sports Sciences Association",

    // ---- TRANSFORMATIONS ----
    trans_tagline: "Real Clients. Real Proof.",
    trans_title: "Client Transformations",
    trans_1_tag: "Fat Loss & Muscle Gain",
    trans_1_duration: "12 Weeks",
    trans_1_name: "Ahmed's Transformation",
    trans_1_desc: "Ahmed reduced body fat from 24% to 11% while gaining solid lean mass, fully rebuilding strength in compound lifts.",
    trans_1_m1_label: "Weight Change:",
    trans_1_m1_val: "-14kg",
    trans_1_m2_label: "Muscle Gained:",
    trans_1_m2_val: "+3.2kg",
    trans_2_tag: "Body Recomposition",
    trans_2_duration: "16 Weeks",
    trans_2_name: "Sarah's Transformation",
    trans_2_desc: "Sarah completely reshaped her posture, sculpted core definition, and improved functional endurance and metabolic rate.",
    trans_2_m1_label: "Weight Change:",
    trans_2_m1_val: "-8.5kg",
    trans_2_m2_label: "Body Fat Change:",
    trans_2_m2_val: "-12.5%",

    // ---- SERVICES ----
    services_tagline: "How We Work Together",
    services_title: "Coaching Architecture",
    svc_1_title: "Bespoke Workout Design",
    svc_1_desc: "No generic PDF files. Every routine is mapped dynamically based on your available equipment, structural biomechanics, joints mobility, and physical targets.",
    svc_2_title: "Caloric & Macro Architecture",
    svc_2_desc: "Science-backed meal planning designed around foods you actually enjoy. Includes customized calculations, hydration formulas, and strategic supplementation guidance.",
    svc_3_title: "Daily Follow-Up & Accountability",
    svc_3_desc: "Direct communication to update weight charts, track training progression logs, evaluate form via videos, and handle dynamic weekly nutrition modifications.",

    // ---- PRICING ----
    pricing_tagline: "Choose Your Pathway",
    pricing_title: "Coaching Programs",
    price_ribbon: "RECOMMENDED",
    pkg_basic_name: "Basic Transformation",
    pkg_basic_period: "/Month",
    pkg_basic_desc: "Perfect for self-motivated individuals needing structured instruction.",
    pkg_elite_name: "Elite Coaching",
    pkg_elite_period: "/Month",
    pkg_elite_desc: "Our flagship accountability model targeting dramatic recomposition.",
    pkg_vip_name: "VIP Ultimate Access",
    pkg_vip_period: "/Month",
    pkg_vip_desc: "Full integration with Coach Mahmoud for maximum priority support.",
    feature_workout: "Customized Workout Program",
    feature_nutrition: "Personalized Nutrition Plan",
    feature_weekly: "Weekly Follow-Up & Adjustments",
    feature_whatsapp: "Daily WhatsApp Chat Support",
    feature_video: "Video Exercise Form Review",
    feature_daily: "Daily Progress Charting",
    feature_priority: "Priority Custom Design Upgrades",
    feature_bespoke: "Bespoke Nutrition & Custom Supplementation",
    feature_unlimited: "Unlimited Video Analysis & Real-time Edits",
    feature_phone: "Direct Phone & Priority WhatsApp Call Access",
    feature_strategy: "Weekly 1-on-1 Strategy Video Consultation",
    btn_select: "Select Plan",
    btn_get_started: "Get Started",
    btn_unlock_vip: "Unlock VIP",

    // ---- WHY ----
    why_tagline: "The Coaching Difference",
    why_title: "Why Coach Mahmoud?",
    why_1_title: "Certified & Scientific",
    why_1_desc: "Fully certified with international qualifications, avoiding standard workout trends in favor of verified biological and hypertrophy science.",
    why_2_title: "100% Tailored Layouts",
    why_2_desc: "I design your charts from zero. Your foods, schedule, and biomechanical parameters form the core structure of your programs.",
    why_3_title: "Fast Accountability Response",
    why_3_desc: "No waiting days for feedback. Updates and corrections are handled with priority so your progress never stalls.",

    // ---- TESTIMONIALS ----
    test_tagline: "Client Success Stories",
    test_title: "What My Clients Say",
    test_1_text: '"Coaching with Mahmoud has been an absolute game changer. I\'ve struggled to lose fat for years while maintaining strength. Within 12 weeks, he completely overhauled my nutrition and custom training program, and the fat literally melted away."',
    test_1_achievement: "Lost 14kg & Gained Muscle",
    test_2_text: '"The level of detail Coach Mahmoud puts into the weekly updates is unmatched. He didn\'t just give me diet rules; he explained the macros, helped me modify choices when traveling, and kept me strictly on track. Recommended for anyone looking for serious results."',
    test_2_achievement: "12.5% Body Fat Reduction",
    test_3_text: '"As a busy professional, finding time to train was impossible. Coach Mahmoud created a highly effective 45-minute home workout program and taught me flexible dieting that fits my schedule. Extremely professional and communicative."',
    test_3_achievement: "Improved Muscle Definition",

    // ---- FAQ ----
    faq_tagline: "Clear Answers",
    faq_title: "Frequently Asked Questions",
    faq_1_q: "How fast will I receive my custom workout and meal plans?",
    faq_1_a: "After you submit your initial fitness assessment form and complete your subscription, Coach Mahmoud will conduct a full analysis of your structure, metabolic history, and schedule. Your personalized training and nutrition blueprints will be delivered directly to your WhatsApp dashboard within 48 to 72 hours.",
    faq_2_q: "Can I train if I only have a home setup or minimal weights?",
    faq_2_a: "Yes. Every training plan is built around the equipment you have available. If you only have resistance bands, dumbbells, or just bodyweight, your routine will be optimized for maximum mechanical tension and hypertrophy using home-specific progressions.",
    faq_3_q: "What if I have foods I absolutely dislike or cannot eat?",
    faq_3_a: "I follow a flexible dieting method backed by strict structural macros. In your assessment form, you will outline all food allergies, preferences, and details. Your meal plan is built to only contain foods you enjoy, ensuring the diet is sustainable long-term.",
    faq_4_q: "How do the weekly check-ins and follow-ups work?",
    faq_4_a: "For standard plans, you will submit a weekly check-in sheet detailing weight parameters, measurements, and training performance. Based on this data, Coach Mahmoud adjusts your macros, caloric density, and workout load. For Elite and VIP plans, this tracking and communication is done daily on WhatsApp.",

    // ---- CONTACT ----
    contact_badge: "START TODAY",
    contact_title: "Ready To Transform Your Body & Mind?",
    contact_desc: "Fill out the rapid biometric questionnaire below. Once submitted, it will compile your stats and redirect you directly to Coach Mahmoud on WhatsApp to finalize your enrollment.",
    contact_whatsapp_label: "WhatsApp Hotline",
    contact_email_label: "Support Email",
    form_title: "Biometric Assessment",
    form_subtitle: "Enter your metrics below to calculate your tailored coach macros.",
    label_name: "Full Name *",
    label_phone: "WhatsApp Number *",
    label_age: "Age *",
    label_height: "Height (cm) *",
    label_weight: "Weight (kg) *",
    label_city: "City & Country *",
    label_package: "Selected Coaching Package *",
    placeholder_name: "Enter your full name",
    placeholder_phone: "e.g. +201012345678",
    placeholder_age: "Age",
    placeholder_height: "cm",
    placeholder_weight: "kg",
    placeholder_city: "e.g. Cairo, Egypt",
    placeholder_package: "Choose a package",
    option_basic: "Basic Transformation - $59/mo",
    option_elite: "Elite Coaching (Recommended) - $99/mo",
    option_vip: "VIP Ultimate Access - $189/mo",
    btn_submit: "Send Biometrics on WhatsApp",

    // ---- FOOTER ----
    footer_brand_desc: "Premium 1-on-1 science-backed coaching. Change your physique, build discipline, and unlock your true performance potential.",
    footer_nav_title: "Navigation",
    footer_nav_home: "Home",
    footer_nav_about: "About",
    footer_nav_trans: "Transformations",
    footer_nav_services: "Services",
    footer_nav_pricing: "Pricing Plans",
    footer_nav_contact: "Contact",
    footer_disclaimer_title: "Medical Disclaimer",
    footer_disclaimer_text: "All fitness routines, metabolic suggestions, and nutrition guidelines provided by Coach Mahmoud Hamada are designed strictly for educational and athletic enhancement. Please consult a qualified health provider before commencing any physical transformation protocol.",
    footer_copy: "© 2026 Coach Mahmoud Hamada. All Rights Reserved.",
    footer_tagline: "Designed for elite athletic training.",
};
